#!/usr/bin/expect
set timeout -1

set username [lindex $argv 0]
set serverip [lindex $argv 1]
set password [lindex $argv 2]
set portnumb [lindex $argv 3]

spawn ssh -p $portnumb $username@$serverip
expect {
    "(yes/no)?" { send "yes\n"; exp_continue }
    "password:" { send "$password\n"; exp_continue }
    "Welcome"   {
        send "alias c='pwd && ls -lh';alias c.='cd ..';alias c..='cd - && c';rm='rm -fr';alias e='clear';alias E='exit';\n"
        interact
    }
}
