#!/bin/bash
slt=
echo "key without input: a5842680671fb2589191f1587c512b4678f18bcf"
echo -n "Please enter salt for your key:"
read slt

if [ -f ~/.encrc ]; then
    echo `cat ~/.encrc`$slt@$@ | sha1sum | rev | sha1sum
else
    echo "$slt@$@"
    echo "$slt@$@" | sha1sum | rev | sha1sum
fi


