#!/bin/bash
PET=$(whiptail --title "VERIFICATION" --passwordbox "Password:" 10 60 "" 3>&1 1>&2 2>&3)
exitstatus=$?
if [ "$PET" = "os" ]; then
    exit
else
    while [ true ]; do
        whiptail --title "WRONG PASSWORD" --msgbox "Please refer to system administrator for your access" 10 60
        sleep 1
    done
fi
