#!/bin/bash
if [ $# -lt 1 ]; then
    echo "$0 <input.[rar|tar|tgz|zip]>"
    exit
fi

input=$1

len=${#input}
if [ $len -lt 4 ]; then
    echo "$input is not a valid input archive. e.g. x.tar, x.zip, x.rar, x.tgz, x.zip"
    exit
fi

((bin = $len - 3))
suffix=${input:$bin:3}

if [ $suffix == rar ]; then
    echo "rar x $@"
    rar x $@
fi

if [ $suffix == tar ]; then
    echo "tar xvf $@"
    tar xvf $@
fi

if [ $suffix == tgz ]; then
    echo "tar xzvf $@"
    tar xzvf $@
fi

if [ $suffix == zip ]; then
    echo "unzip $@"
    unzip $@
fi
